# Wrapper for level-3 BLIS routines.
#

@blis_ccall_group("gemm",  Cvoid, (BliTrans,
                                   BliTrans,
                                   BliDim,
                                   BliDim,
                                   BliDim,
                                   Ptr{xType},
                                   Ptr{xType}, BliInc, BliInc,
                                   Ptr{xType}, BliInc, BliInc,
                                   Ptr{xType},
                                   Ptr{xType}, BliInc, BliInc)) 
@blis_ccall_group("hemm",  Cvoid, (BliSide,
                                   BliUpLo,
                                   BliConj,
                                   BliTrans,
                                   BliDim,
                                   BliDim,
                                   Ptr{xType},
                                   Ptr{xType}, BliInc, BliInc,
                                   Ptr{xType}, BliInc, BliInc,
                                   Ptr{xType},
                                   Ptr{xType}, BliInc, BliInc))
@blis_ccall_group("herk",  Cvoid, (BliUpLo,
                                   BliTrans,
                                   BliDim,
                                   BliDim,
                                   Ptr{rType},
                                   Ptr{xType}, BliInc, BliInc,
                                   Ptr{rType},
                                   Ptr{xType}, BliInc, BliInc))
@blis_ccall_group("her2k", Cvoid, (BliUpLo,
                                   BliTrans,
                                   BliDim,
                                   BliDim,
                                   Ptr{xType},
                                   Ptr{xType}, BliInc, BliInc,
                                   Ptr{xType}, BliInc, BliInc,
                                   Ptr{rType},
                                   Ptr{xType}, BliInc, BliInc))
@blis_ccall_group("symm",  Cvoid, (BliSide,
                                   BliUpLo,
                                   BliConj,
                                   BliTrans,
                                   BliDim,
                                   BliDim,
                                   Ptr{xType},
                                   Ptr{xType}, BliInc, BliInc,
                                   Ptr{xType}, BliInc, BliInc,
                                   Ptr{xType},
                                   Ptr{xType}, BliInc, BliInc))
@blis_ccall_group("syrk",  Cvoid, (BliUpLo,
                                   BliTrans,
                                   BliDim,
                                   BliDim,
                                   Ptr{xType},
                                   Ptr{xType}, BliInc, BliInc,
                                   Ptr{xType},
                                   Ptr{xType}, BliInc, BliInc))
@blis_ccall_group("syr2k", Cvoid, (BliUpLo,
                                   BliTrans,
                                   BliDim,
                                   BliDim,
                                   Ptr{xType},
                                   Ptr{xType}, BliInc, BliInc,
                                   Ptr{xType}, BliInc, BliInc,
                                   Ptr{xType},
                                   Ptr{xType}, BliInc, BliInc))
@blis_ccall_group("trmm",  Cvoid, (BliSide,
                                   BliUpLo,
                                   BliTrans,
                                   BliDiag,
                                   BliDim,
                                   BliDim,
                                   Ptr{xType},
                                   Ptr{xType}, BliInc, BliInc,
                                   Ptr{xType}, BliInc, BliInc))
@blis_ccall_group("trmm3", Cvoid, (BliSide,
                                   BliUpLo,
                                   BliTrans,
                                   BliDiag,
                                   BliTrans,
                                   BliDim,
                                   BliDim,
                                   Ptr{xType},
                                   Ptr{xType}, BliInc, BliInc,
                                   Ptr{xType}, BliInc, BliInc,
                                   Ptr{xType},
                                   Ptr{xType}, BliInc, BliInc))
@blis_ccall_group("trsm",  Cvoid, (BliSide,
                                   BliUpLo,
                                   BliTrans,
                                   BliDiag,
                                   BliDim,
                                   BliDim,
                                   Ptr{xType},
                                   Ptr{xType}, BliInc, BliInc,
                                   Ptr{xType}, BliInc, BliInc))

