# Wrapper for level-1 BLIS fused-vector routines.
#

@blis_ccall_group(axpy2v,
                  Cvoid,
                  conjx,  BliConj,
                  conjy,  BliConj,
                  m,      BliDim,
                  αx,     Ptr{xType},
                  αy,     Ptr{xType},
                  x,      Ptr{xType}, incx, BliInc,
                  y,      Ptr{xType}, incy, BliInc,
                  z,      Ptr{xType}, incz, BliInc)
@blis_ccall_group(dotaxpyv,
                  Cvoid,
                  conjxt, BliConj,
                  conjx,  BliConj,
                  conjy,  BliConj,
                  m,      BliDim,
                  α,      Ptr{xType},
                  x,      Ptr{xType}, incx, BliInc,
                  y,      Ptr{xType}, incy, BliInc,
                  ρ,      Ptr{xType},
                  z,      Ptr{xType}, incz, BliInc)
@blis_ccall_group(axpyf,
                  Cvoid,
                  conja,  BliConj,
                  conjx,  BliConj,
                  m,      BliDim,
                  b,      BliDim,
                  α,      Ptr{xType},
                  a,      Ptr{xType}, inca, BliInc, lda, BliInc,
                  x,      Ptr{xType}, incx, BliInc,
                  y,      Ptr{xType}, incy, BliInc)
@blis_ccall_group(dotxf,
                  Cvoid,
                  conjat, BliConj,
                  conjx,  BliConj,
                  m,      BliDim,
                  b,      BliDim,
                  α,      Ptr{xType},
                  a,      Ptr{xType}, inca, BliInc, lda, BliInc,
                  x,      Ptr{xType}, incx, BliInc,
                  β,      Ptr{xType},
                  y,      Ptr{xType}, incy, BliInc)
@blis_ccall_group(dotxaxpyf,
                  Cvoid,
                  conjat, BliConj,
                  conja,  BliConj,
                  conjw,  BliConj,
                  conjx,  BliConj,
                  m,      BliDim,
                  b,      BliDim,
                  α,      Ptr{xType},
                  a,      Ptr{xType}, inca, BliInc, lda, BliInc,
                  w,      Ptr{xType}, incw, BliInc,
                  x,      Ptr{xType}, incx, BliInc,
                  β,      Ptr{xType},
                  y,      Ptr{xType}, incy, BliInc,
                  z,      Ptr{xType}, incz, BliInc)

