# Wrapper for level-2 BLIS routines.
#

@blis_ccall_group("gemv",  Cvoid, (BliTrans,
                                   BliConj,
                                   BliDim,
                                   BliDim,
                                   Ptr{xType},
                                   Ptr{xType}, BliInc, BliInc,
                                   Ptr{xType}, BliInc,
                                   Ptr{xType},
                                   Ptr{xType}, BliInc)) 
@blis_ccall_group("ger",   Cvoid, (BliConj,
                                   BliConj,
                                   BliDim,
                                   BliDim,
                                   Ptr{xType},
                                   Ptr{xType}, BliInc,
                                   Ptr{xType}, BliInc,
                                   Ptr{xType}, BliInc, BliInc))
@blis_ccall_group("hemv",  Cvoid, (BliUpLo,
                                   BliConj,
                                   BliConj,
                                   BliDim,
                                   Ptr{xType},
                                   Ptr{xType}, BliInc, BliInc,
                                   Ptr{xType}, BliInc,
                                   Ptr{xType},
                                   Ptr{xType}, BliInc))
@blis_ccall_group("her",   Cvoid, (BliUpLo,
                                   BliConj,
                                   BliDim,
                                   Ptr{rType},
                                   Ptr{xType}, BliInc,
                                   Ptr{xType}, BliInc, BliInc))
@blis_ccall_group("her2",  Cvoid, (BliUpLo,
                                   BliConj,
                                   BliConj,
                                   BliDim,
                                   Ptr{xType},
                                   Ptr{xType}, BliInc,
                                   Ptr{xType}, BliInc,
                                   Ptr{xType}, BliInc, BliInc))
@blis_ccall_group("symv",  Cvoid, (BliUpLo,
                                   BliConj,
                                   BliConj,
                                   BliDim,
                                   Ptr{xType},
                                   Ptr{xType}, BliInc, BliInc,
                                   Ptr{xType}, BliInc,
                                   Ptr{xType},
                                   Ptr{xType}, BliInc))
@blis_ccall_group("syr",   Cvoid, (BliUpLo,
                                   BliConj,
                                   BliDim,
                                   Ptr{xType},
                                   Ptr{xType}, BliInc,
                                   Ptr{xType}, BliInc, BliInc))
@blis_ccall_group("syr2",  Cvoid, (BliUpLo,
                                   BliConj,
                                   BliConj,
                                   BliDim,
                                   Ptr{xType},
                                   Ptr{xType}, BliInc,
                                   Ptr{xType}, BliInc,
                                   Ptr{xType}, BliInc, BliInc))
@blis_ccall_group("trmv",  Cvoid, (BliUpLo,
                                   BliTrans,
                                   BliDiag,
                                   BliDim,
                                   Ptr{xType},
                                   Ptr{xType}, BliInc, BliInc,
                                   Ptr{xType}, BliInc))
@blis_ccall_group("trsv",  Cvoid, (BliUpLo,
                                   BliTrans,
                                   BliDiag,
                                   BliDim,
                                   Ptr{xType},
                                   Ptr{xType}, BliInc, BliInc,
                                   Ptr{xType}, BliInc))

